import { DEFAULT_SHARE_CARD_TEMPLATE, toShareCardSections, type ShareCardData } from "./card-template";

function short(text: string, max = 220): string {
  return text;
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export function buildShareCardPngDataUrl(data: ShareCardData): string {
  const template = DEFAULT_SHARE_CARD_TEMPLATE;
  const canvas = document.createElement("canvas");
  canvas.width = template.width;
  canvas.height = template.height;

  const ctx = canvas.getContext("2d");
  if (!ctx) {
    throw new Error("Canvas unavailable");
  }

  // Panel-like background (soft gradient)
  const gradient = ctx.createLinearGradient(0, 0, template.width, template.height);
  gradient.addColorStop(0, template.backgroundStart);
  gradient.addColorStop(1, template.backgroundEnd);
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, template.width, template.height);

  // Card container (white, rounded)
  const cardX = 80;
  const cardY = 60;
  const cardW = template.width - 160;
  const cardH = template.height - 120;
  ctx.save();
  ctx.beginPath();
  ctx.moveTo(cardX + 32, cardY);
  ctx.lineTo(cardX + cardW - 32, cardY);
  ctx.quadraticCurveTo(cardX + cardW, cardY, cardX + cardW, cardY + 32);
  ctx.lineTo(cardX + cardW, cardY + cardH - 32);
  ctx.quadraticCurveTo(cardX + cardW, cardY + cardH, cardX + cardW - 32, cardY + cardH);
  ctx.lineTo(cardX + 32, cardY + cardH);
  ctx.quadraticCurveTo(cardX, cardY + cardH, cardX, cardY + cardH - 32);
  ctx.lineTo(cardX, cardY + 32);
  ctx.quadraticCurveTo(cardX, cardY, cardX + 32, cardY);
  ctx.closePath();
  ctx.fillStyle = "#fff";
  ctx.shadowColor = "rgba(0,0,0,0.06)";
  ctx.shadowBlur = 24;
  ctx.fill();
  ctx.restore();

  // Title
  ctx.fillStyle = template.textPrimary;
  ctx.font = "700 48px 'Inter', 'Segoe UI', sans-serif";
  ctx.fillText("CultureLens", cardX + 48, cardY + 90);

  // Query
  ctx.font = "600 28px 'Inter', 'Segoe UI', sans-serif";
  ctx.fillStyle = template.accent;
  ctx.fillText(short(data.query, 70), cardX + 48, cardY + 150);

  // Sections (Reference, Origin, etc.)
  const sections = toShareCardSections(data);
  let top = cardY + 210;
  for (const section of sections) {
    ctx.font = "700 22px 'Inter', 'Segoe UI', sans-serif";
    ctx.fillStyle = template.textMuted;
    ctx.fillText(section.label, cardX + 48, top);

    ctx.font = "400 26px 'Inter', 'Segoe UI', sans-serif";
    ctx.fillStyle = template.textPrimary;
    // Multi-line wrapping for content
    const words = section.value.split(' ');
    let line = '';
    let y = top + 38;
    const maxWidth = cardW - 96;
    for (let i = 0; i < words.length; i++) {
      const testLine = line + words[i] + ' ';
      const { width } = ctx.measureText(testLine);
      if (width > maxWidth && line !== '') {
        ctx.fillText(line.trim(), cardX + 48, y);
        line = words[i] + ' ';
        y += 34;
      } else {
        line = testLine;
      }
    }
    if (line) ctx.fillText(line.trim(), cardX + 48, y);
    top = y + 32;
  }

  // Footer
  ctx.fillStyle = template.textMuted;
  ctx.font = "700 20px 'Inter', 'Segoe UI', sans-serif";
  ctx.fillText("Generated by CultureLens", cardX + 48, cardY + cardH - 32);

  return canvas.toDataURL("image/png");
}

export function buildShareCardSvg(data: ShareCardData): string {
  const template = DEFAULT_SHARE_CARD_TEMPLATE;
  const sections = toShareCardSections(data);
  // Card container
  const cardX = 80;
  const cardY = 60;
  const cardW = template.width - 160;
  const cardH = template.height - 120;
  // Multi-line wrapping for SVG
  function wrapSvgText(text: string, x: number, y: number, fontSize: number, maxWidth: number) {
    const words = text.split(' ');
    let lines: string[] = [];
    let line = '';
    // Approximate char width for font size 26: 0.6em
    const maxChars = Math.floor(maxWidth / (fontSize * 0.6));
    for (let i = 0; i < words.length; i++) {
      const testLine = line + words[i] + ' ';
      if (testLine.length > maxChars && line !== '') {
        lines.push(line.trim());
        line = words[i] + ' ';
      } else {
        line = testLine;
      }
    }
    if (line) lines.push(line.trim());
    return lines.map((l, idx) => `<tspan x="${x}" y="${y + idx * (fontSize + 8)}">${escapeXml(l)}</tspan>`).join('');
  }
  const sectionRows = sections
    .map((section, idx) => {
      const baseY = cardY + 210 + idx * 90;
      const contentY = baseY + 38;
      return `
        <text x="${cardX + 48}" y="${baseY}" font-size="22" font-weight="700" fill="${template.textMuted}" font-family="'Inter', 'Segoe UI', sans-serif">${escapeXml(section.label)}</text>
        <text font-size="26" fill="${template.textPrimary}" font-family="'Inter', 'Segoe UI', sans-serif">${wrapSvgText(section.value, cardX + 48, contentY, 26, cardW - 96)}</text>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${template.width}" height="${template.height}" viewBox="0 0 ${template.width} ${template.height}">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${template.backgroundStart}"/>
      <stop offset="100%" stop-color="${template.backgroundEnd}"/>
    </linearGradient>
    <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="4" stdDeviation="12" flood-color="#000" flood-opacity="0.06"/>
    </filter>
  </defs>
  <rect x="0" y="0" width="${template.width}" height="${template.height}" fill="url(#bg)"/>
  <rect x="${cardX}" y="${cardY}" width="${cardW}" height="${cardH}" rx="32" fill="#fff" filter="url(#shadow)"/>
  <text x="${cardX + 48}" y="${cardY + 90}" font-size="48" font-weight="700" fill="${template.textPrimary}" font-family="'Inter', 'Segoe UI', sans-serif">CultureLens</text>
  <text x="${cardX + 48}" y="${cardY + 150}" font-size="28" font-weight="600" fill="${template.accent}" font-family="'Inter', 'Segoe UI', sans-serif">${escapeXml(short(data.query, 70))}</text>
  ${sectionRows}
  <text x="${cardX + 48}" y="${cardY + cardH - 32}" font-size="20" font-weight="700" fill="${template.textMuted}" font-family="'Inter', 'Segoe UI', sans-serif">Generated by CultureLens</text>
</svg>`;
}
